# file: roles/aws.infra.ansible/tasks/aws_infra_create.yml
---

#---------------------------------------------------
#  VPC
#---------------------------------------------------
- name: Create a AWS VPC with a public subnet
  ec2_vpc_net:
    name:        "{{ name }}"
    tags:        "{{ vpc_resource_tags }}"
    region:      "{{ region }}"
    cidr_block:  10.0.0.0/16
    dns_support: true
  register: vpc
  tags:
    - vpc_create

- name: debug module.
  debug: 
    var: vpc

- set_fact:
      aws_vpc_id: "{{ vpc.vpc.id }}"

- name: debug module.
  debug: 
    var: aws_vpc_id

#---------------------------------------------------
#  Create Subnet
#---------------------------------------------------
- name: Create subnet 
  ec2_vpc_subnet:
    state:  present
    cidr:   10.0.0.0/20
    vpc_id: "{{ aws_vpc_id }}"
    az:     "{{ az }}"
    tags:   "{{ subnet_resource_tags }}"
    region: "{{ region }}"
  register: subnet
  tags:
    - vpc_create

- set_fact:
      aws_subnet_id: "{{ subnet.subnet.id }}"

#---------------------------------------------------
#  IGW
#---------------------------------------------------
- name: Create IGW
  ec2_vpc_igw:
    state:  present
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ region }}"
    tags: "{{ igw_resource_tags }}"
  register: igw
  tags:
    - vpc_create

- set_fact:
      aws_igw_id: "{{ igw.gateway_id }}"

#---------------------------------------------------
#  Route Table
#---------------------------------------------------
- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ region }}"
    tags:   "{{ route_resource_tags }}"
    subnets:
      - "{{ aws_subnet_id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ aws_igw_id }}"
  register: public_route_table

#---------------------------------------------------
#  NACL
#---------------------------------------------------
# - name: "Remove the ingress and egress rules - defaults to deny all"
#   ec2_vpc_nacl:
#     vpc_id: "{{ aws_vpc_id }}"
#     name: "{{ nacl_name }}"
#     region: "{{ region }}"

#---------------------------------------------------
#  Security Groups
#---------------------------------------------------
- name: Security group
  ec2_group:
    description: EC2 security group
    name:   "{{ sg_name }}"
    vpc_id: "{{ aws_vpc_id }}"
    region: "{{ region }}"
    tags: "{{ sg_resource_tags }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: all
        to_port: all
        cidr_ip: 0.0.0.0/0
  register: sec_group

#---------------------------------------------------
#  EC2 
#---------------------------------------------------
- name: Launch EC2 Instance
  ec2:
    wait: yes
    exact_count: 1
    region: "{{ region }}"
    image: "{{ workshop_ami }}"
    key_name: "{{ workshop_keypair }}"
    group_id: "{{ sec_group.group_id }}"
    instance_type: "{{ workshop_instance_type }}"
    assign_public_ip: "{{ workshop_public_ip }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
    count_tag:
      Name: "{{ workshop_instance_tag }}"
    instance_tags:
      Name: "{{ workshop_instance_tag }}"
      StopGroup: "OfficeHoursTerminator"
      DeleteTag: "ATW"
      SecurityGroup: "DISA_STIG_RHEL_7"
    vpc_subnet_id: "{{ aws_subnet_id }}"
  register: ec2_instance
  tags:
    - vpc_create


#---------------------------------------------------
#  SSH Key
#---------------------------------------------------
# - name: Check for existing key and remove
#   ec2_key: name="{{ workshop_keypair }}" region="{{ region }}" state=absent
#   tags:
#     - vpc_create

# - name: Create EC2 keypair
#   ec2_key: name="{{ containerworkshop_keypair }}" region="{{ region }}" state=present
#   register: ec2_key
#   tags:
#     - vpc_create

# - debug: var=ec2_key
#   tags:
#     - vpc_create

# - name: Create ssh keypair
#   copy: 
#     content: "{{ ec2_key.key.private_key }}"
#     dest:    "{{ ssh_key_path }}/{{ containerworkshop_keypair }}"
#     mode:    0400
#   tags:
#     - vpc_create