# file: roles/aws.infra.ansible/tasks/aws_infra_destroy.yml
---

# AWS EC2
- name: Filter For EC2 Instances By Tags
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      "tag:DeleteTag": ATW
  register: aws_ec2_facts
  tags: 
    - vpc_destroy

- name: debug instance id
  debug: var=aws_ec2_facts.instances[0].id
  tags: 
    - vpc_destroy

#####################################################
# Get VPC + Subnet + Route Table Facts 
#####################################################
# AWS VPCs
- ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:DeleteTag": ATW
  register: aws_vpc_facts 
  tags: 
    - vpc_destroy

- set_fact:
    vpc_delete_id: "{{ aws_vpc_facts.vpcs[0].id }}"
  tags: 
    - vpc_destroy

- set_fact:
    vpc_delete_name: "{{ aws_vpc_facts.vpcs[0].tags.Name }}"
  tags: 
    - vpc_destroy

- set_fact:
    vpc_delete_cidr_block: "{{ aws_vpc_facts.vpcs[0].cidr_block }}"
  tags: 
    - vpc_destroy

# AWS Subnets
- ec2_vpc_subnet_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_delete_id }}"
  register: aws_subnet_facts
  tags: 
    - vpc_destroy

# AWS Route Tables
- ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_delete_id }}"
  register: aws_route_tables
  tags: 
    - vpc_destroy

# AWS Security Group
- ec2_group_facts:
    region: "{{ region }}"
    filters:
      vpc-id: "{{ vpc_delete_id }}"
  register: aws_sec_group
  tags: 
    - vpc_destroy

#AWS NACL
- name: Get All NACLs
  register: all_nacls
  ec2_vpc_nacl_facts:
    region: "{{ region }}"
  tags: 
    - vpc_destroy

#####################################################
# DEBUG
#####################################################

- name: debug vpc facts
  debug: var=aws_vpc_facts
  tags: 
    - vpc_destroy

- name: debug vpc facts
  debug: var=vpc_delete_id
  tags: 
    - vpc_destroy

- name: debug vpc facts
  debug: var=vpc_delete_name
  tags: 
    - vpc_destroy

- name: debug vpc facts
  debug: var=vpc_delete_cidr_block
  tags: 
    - vpc_destroy

- name: debug subnet facts
  debug: var=aws_subnet_facts
  tags: 
    - vpc_destroy
    
- name: debug route facts
  debug: var=aws_route_tables
  tags: 
    - vpc_destroy

- name: debug sec group facts
  debug: var=aws_sec_group
  tags: 
    - vpc_destroy

- name: debug nacls
  debug: var=all_nacls
  tags: 
    - vpc_destroy

#####################################################
# DELETE 
#####################################################
- name: Terminate EC2 instances that were previously launched
  ec2:
    state: 'absent'
    region: "{{ region }}"
    instance_ids: '{{ aws_ec2_facts.instances[0].id }}'
  tags: 
    - vpc_destroy

- name: Pause for EC2 instance to delete
  pause:
    seconds: "30"

- name: Delete Sec Group
  ec2_group:
    name: ""
    region: "{{ region }}"
    vpc_id: "{{ vpc_delete_id }}"
    state: absent
  tags: 
    - vpc_destroy

- name: Delete NACL
  ec2_vpc_nacl:
    name: ""
    region: "{{ region }}"
    vpc_id: "{{ vpc_delete_id }}"
    state: absent
  tags: 
    - vpc_destroy

- name: Delete Route Table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_delete_id }}"
    region: "{{ region }}"
    state: absent
  tags: 
    - vpc_destroy   

- name: Delete IGW
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc_delete_id }}"
    state: absent
  tags: 
    - vpc_destroy   

- name: Delete Subnet 
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_delete_id }}"
    cidr: "{{ cidr_block }}"
    region: "{{ region }}"
    state: absent
  tags: 
    - vpc_destroy

- name: Delete VPC
  ec2_vpc_net:
    name: "{{ vpc_delete_name }}"
    region: "{{ region }}"
    cidr_block: "{{ vpc_delete_cidr_block }}"
    resource_tags: { DeleteTag: "ATW" }
    state: absent
  tags: 
    - vpc_destroy