---
- name: Inventory Sync
  hosts: localhost
  connection: local
  gather_facts: false
  become: no

  tasks:
  #---------------------------------------------------
  # Update autmaticly the inventory in Tower
  #---------------------------------------------------
    - name: Inventory in Tower is set to update on launch. This just is a step to sync.
      command: time