# file: roles/firewalld/tasks/main.yml
---
- firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled


- firewalld:
    port: 22/tcp
    permanent: true
    state: enabled

- name: Bounce firewalld
  service: name=firewalld state=restarted