# tasks file for kickoff_tower_workflow
---

- name: Job Template to destroy a Workflow Job Template
  uri:
    url: https://ansible1-d4a1.rhpds.opentlc.com/api/v2/workflow_job_templates/28/launch/
    method: POST
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    url_username: "{{ tower_user }}"
    url_password: "{{ tower_pass }}"
    force_basic_auth: yes
    body:
      user: "{{ tower_user }}"
      password: "{{ tower_pass }}"
    body_format: json
    validate_certs: False
    headers:
      Content-Type: "application/json"
    status_code: 200, 201